architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian bookworm amd64 (20260521_05:24)
  image.os: Debian
  image.release: bookworm
  image.serial: "20260521_05:24"
  image.type: squashfs
  image.variant: default
  volatile.base_image: 8c9caec644420bbc2bff896a501715290bbbed3a572b6a742a5e53910b12aa62
  volatile.cloud-init.instance-id: d2ff67db-899c-4de0-86f1-8baf834f69da
  volatile.eth0.host_name: vethac6e10af
  volatile.eth0.hwaddr: 10:66:6a:2d:25:06
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 45be88d7-2501-4d62-857b-c9a83c96c0a8
  volatile.uuid.generation: 45be88d7-2501-4d62-857b-c9a83c96c0a8
devices:
  cockroach-ui:
    connect: tcp:10.245.23.52:8080
    listen: tcp:0.0.0.0:8081
    type: proxy
ephemeral: false
profiles:
  - default
stateful: false
description: ""
